var CongaPackageTransformUtil = Class.create();
CongaPackageTransformUtil.prototype = {
	initialize: function() {
	},
	getUserName: function (name) {
		//gs.info('pkgutil ' + name );
		var userName = {};
		
		var iFirstSpace = name.indexOf(' ');
		
		userName.firstName = name.substring(0,iFirstSpace);
		userName.sureName = name.substring(iFirstSpace);
		
		return userName;
		
	},
	// test if sUseID is unique user_name. If not, new user_name is generated by adding number
	getUniqueUserID: function (sUserID) {
		var userID = sUserID.toLowerCase();
		var userIdArray = [];
		
		var sysUserGr = new GlideRecord('sys_user');
		sysUserGr.addQuery('user_name', 'STARTSWITH', userID);
		sysUserGr.query();
		
		while (sysUserGr.next()) {
			userIdArray.push(sysUserGr.user_name + '');
		}
		
		if (userIdArray.length > 0) {
			var isUnique = false;
			var i = 0;
			var tmpUserID = userID;
			// i < 10000 to prevent infinite loop
			while (!isUnique && i < 10000) {
				if (userIdArray.indexOf(tmpUserID) > -1) {
					//gs.info('userID ' + tmpUserID + ' already exist. Generating new userID.');
					tmpUserID = userID + (++i);
					
				} else {
					userID = tmpUserID;
					isUnique = true;
					//gs.info('userId ' + userID + ' is unique.');
				}
			}
		}
		
		return userID;
		
	},
	
	getCustomerOUID: function() {
		//return gs.getProperty('x_cir.customer_package_import.customer_ou');

	},
	
	getCompanyID: function() {
		return gs.getProperty('x_cir.customer_package_import.company');
	},
	/*
	crateAppToCustomerOURelationship: function (source){
		var logString =  'row ' + source.sys_import_row +' - crateAppToCustomerOURelationship: ';
		var customerOUID = this.getCustomerOUID();
		var cirAppGR = this.getCIRApplication(source);
		
		if (cirAppGR != null) {
			// log.info(logString + 'row ' + source.sys_import_row + ' - app exists: ' + cirAppGR.sys_id + ' ' + cirAppGR.cir_name);
			var cirApptoCOUGR = new GlideRecord('x_cir_m2m_cir_apps_customer_ous');
			cirApptoCOUGR.addQuery('cir_application',cirAppGR);
			cirApptoCOUGR.addQuery('customer_ou', customerOUID);
			cirApptoCOUGR.query();
			
			if (!cirApptoCOUGR.hasNext()) {
				
				var newCirApptoCOUGR = new GlideRecord('x_cir_m2m_cir_apps_customer_ous');
				newCirApptoCOUGR.initialize();
				newCirApptoCOUGR.cir_application = cirAppGR.sys_id;
				newCirApptoCOUGR.customer_ou = customerOUID;
				newCirApptoCOUGR.insert();
				
			}
		}
		
	},
	*/
	//Enhanced method - CONGA-292

	crateAppToCustomerOURelationship: function (user, app){

		
		if (user && app) {
			// log.info(logString + 'row ' + source.sys_import_row + ' - app exists: ' + cirAppGR.sys_id + ' ' + cirAppGR.cir_name);
			var cirApptoCOUGR = new GlideRecord('x_cir_m2m_cir_apps_customer_ous');
			cirApptoCOUGR.addQuery('cir_application', app);
			cirApptoCOUGR.addQuery('customer_ou', user);
			cirApptoCOUGR.query();
			
			if (!cirApptoCOUGR.hasNext()) {
				
				var newCirApptoCOUGR = new GlideRecord('x_cir_m2m_cir_apps_customer_ous');
				newCirApptoCOUGR.initialize();
				newCirApptoCOUGR.cir_application = app;
				newCirApptoCOUGR.customer_ou = user;
				newCirApptoCOUGR.insert();
				
			}
		}
		
	},
	createAppToCustomerAVRelationship: function(appID, userEmail) {
		
		var companyID = gs.getProperty('x_cir.customer_package_import.company');
		
		var userRec = new GlideRecord('sys_user');
		userRec.addQuery('email', userEmail);
		userRec.query();
		
		if(userRec.next()) {
			var relRecQuery = new GlideRecord('x_cir_m2m_companies_cir_app');
			relRecQuery.addQuery('company', companyID);
			relRecQuery.addQuery('cir_application', appID);
			relRecQuery.addQuery('user', userRec.sys_id);
			relRecQuery.query();
			if(!relRecQuery.next()) {
				var relRec = new GlideRecord('x_cir_m2m_companies_cir_app');
				relRec.initialize();
				relRec.cir_application = appID;
				relRec.user = userRec.sys_id;
				relRec.company = companyID;
				relRec.insert();
			}					 				
		}
	},
	
	createAppToCustomerOURelationship: function (appID) {
		var ouID = gs.getProperty('x_cir.customer_package_import.customer_ou');
		
		var queryRec = new GlideRecord('x_cir_m2m_cir_apps_customer_ous');
		queryRec.addQuery('cir_application', appID);
		queryRec.addQuery('customer_ou', ouID);
		queryRec.query();
		if(!queryRec.next()) {
			var relRec = new GlideRecord('x_cir_m2m_cir_apps_customer_ous');
			relRec.initialize();
			relRec.cir_application = appID;
			relRec.customer_ou = ouID;
			relRec.insert();
		}
	},
	
	
	crateAppToCompanyRelationship: function (source){
		var logString =  'row ' + source.sys_import_row +' - crateAppToCompanyRelationship: ';
		var comapnyID = this.getCompanyID();
		var cirAppGR = this.getCIRApplication(source);
		
		
		if (cirAppGR != null) {
			// log.info(logString + 'App exists: ' + cirAppGR.sys_id + ' ' + cirAppGR.cir_name);
			var cirApptoCOUGR = new GlideRecord('x_cir_m2m_companies_cir_app');
			cirApptoCOUGR.addQuery('cir_application',cirAppGR);
			cirApptoCOUGR.addQuery('company', comapnyID);
			cirApptoCOUGR.query();
			
			if (!cirApptoCOUGR.hasNext()) {
				
				var newCirApptoCOUGR = new GlideRecord('x_cir_m2m_companies_cir_app');
				newCirApptoCOUGR.initialize();
				newCirApptoCOUGR.cir_application = cirAppGR.sys_id;
				newCirApptoCOUGR.company = comapnyID;
				newCirApptoCOUGR.insert();
				
			}
		}
		
	}, 
	
	getApplicationID: function(source) {
		var appID = '';
		var applicationName =  source.u_manufacturer_name.trim() + " " 
			+ source.u_application_name.trim() + " "  + source.u_version.trim() + " ";
		
		var bitIndex = source.u_bitedition.indexOf('-');
		var bitEdition = source.u_bitedition.substring(0, bitIndex);
		applicationName = applicationName + bitEdition;
		
		var cirApp = new GlideRecord('x_cir_cir_application');
		//cirAppGR.addQuery('cir_name',cirAppName);
		cirApp.addQuery('application_name', source.u_application_name);
		cirApp.addQuery('version', source.u_version);
		cirApp.addQuery('manufacturer_name.name', source.u_manufacturer_name);
		cirApp.query();
		if(cirApp.next()) {
			appID = cirApp.sys_id;
			gs.info("cklu>>> application found");
		}
		else {
			gs.info("cklu>>> application not found");
		}
		return appID;
		
	},
	
	getBitEdition: function (bitEd) {
		var bit = bitEd.split('-');
		//return (bit[0] + " " + bit[1] + "s");
		gs.info("cklu>>> BIT" + bit[0]);
		return bit[0];
	},
	
	getCIRApplication: function(source) {
		var retVal = null;
		var cirAppName = source.u_manufacturer_name.trim() + ' ' + source.u_application_name.trim() + ' ' + source.u_version.trim() + ' ' + source.u_bitedition.trim();
		var cirAppGR = new GlideRecord('x_cir_cir_application');
		cirAppGR.addQuery('cir_name', cirAppName);
		cirAppGR.query();
		if (cirAppGR.next()) {
			retVal =  cirAppGR;
		}
		
		return retVal;
	},
	
	//returns true  if value is existing value in choice field
	isChoiceValid: function(field, value) {
		var isValid = false;
		var fieldType = field.getInternalType(); 
		
		if (fieldType == 'choice' ) {
			var choices = field.getChoices();
			if (choices.indexOf(value) > -1) {
				isChoiceValid = true;
			}
		}
		return isChoiceValid;
	},
	
	type: 'CongaPackageTransformUtil'
};